module.exports={
    HOST:"localhost",
    PORT:"1434",
    USER:"amani",
    PASSWORD:"amani",
    DB:"nodetestdb",
    dialect:"mssql",
    pool:{
        max:5,
        min:0,
        acquire:30000,
        idle:10000
    }
};